Factory/Models/Engineer.cs
using System.Collections.Generic;
using System;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int EngineerId { get; set; }
    public string Name { get; set; }
    public Decimal Pay { get; set; }
    public DateTime DateStarted { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/EngineerController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class EngineerController : Controller
  {
    private readonly FactoryContext _db;

    public EngineerController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
        .Include(Engineer => Engineer.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(Engineer => Engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      bool alreadyExists = _db.EngineerMachine.Any(engineerMachine => engineerMachine.EngineerId == engineer.EngineerId && engineerMachine.MachineId == MachineId);
      if (MachineId != 0 && !alreadyExists)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      if (alreadyExists)
      {
        return RedirectToAction("AddEngineerError");
      }
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineer/AddMachine.cshtml
@model Factory.Models.Engineer

<h2>Add a licenced Machine</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("select Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save">
}

Factory/Views/Engineer/AddMachineError.cshtml
<h1>Error: That Machine was already added to this Engineer.</h1>

Factory/Views/Engineer/Create.cshtml
@model Factory.Models.Engineer

<h4>Add New Engineer</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Pay)
  @Html.EditorFor(model => model.Pay)

  @Html.LabelFor(model => model.DateStarted)
  @Html.TextBoxFor(model => model.DateStarted, "{0:yyyy-MM-dd}", new {@type = "date"})

  <input type="submit" value="Add a new engineer" />
}

Factory/Views/Engineer/Delete.cshtml
@model Factory.Models.Engineer

<h2>Are you sure you want to remove this engineer?: @Html.DisplayFor(model => model.Name)</h2>

@using (Html.BeginForm())
{
  <button type="submit">Delete Engineer</button>
}

Factory/Views/Engineer/Details.cshtml
@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<p>@Html.DisplayNameFor(model => model.Pay): $@Html.DisplayFor(model => model.Pay) per hour</p>
<p>@Html.DisplayNameFor(model => model.DateStarted): @Html.DisplayFor(model => model.DateStarted.Month)/@Html.DisplayFor(model => model.DateStarted.Day)/@Html.DisplayFor(model => model.DateStarted.Year)</p>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This Engineer is not Licened to repair any Machines</p>
}
else
{
  <h4>Assigned Machines</h4>
  @foreach(var join in Model.JoinEntities)
  {
    <li>
      @join.Machine.Name
    </li>
      @using (Html.BeginForm("DeleteMachine", "Engineer"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" />
      }
  }
}

<p>@Html.ActionLink("Edit this engineer", "Edit", new{ id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete this engineer", "Delete", new{ id = Model.EngineerId })</p>
<p>@Html.ActionLink("Asign a machine to this engineer", "AddMachine", new { id = Model.EngineerId })</p>

Factory/Views/Engineer/Edit.cshtml
@model Factory.Models.Engineer

<h4>Add New Engineer</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Pay)
  @Html.EditorFor(model => model.Pay)

  @Html.LabelFor(model => model.DateStarted)
  @Html.TextBoxFor(model => model.DateStarted, "{0:yyyy-MM-dd}", new {@type = "date"})

  <input type="submit" value="Add a new engineer" />
}

Factory/Views/Engineer/Index.cshtml
@using Factory.Models;
@model List<Factory.Models.Engineer>

<h1>Engineer</h1>
@if(@Model.Count == 0)
{
  <p>No Engineers have been added</p>
}
<ul>
  @foreach(Engineer engineer in Model)
  {
    <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
  }
</ul>

<p>@Html.ActionLink("Add a new engineer", "Create")</p>