Factory/Models/Machine.cs
using System.Collections.Generic;
using System;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int MachineId { get; set; }
    public string Name { get; set; }
    public Boolean Operational { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/MachineController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class MachineController : Controller
  {
    private readonly FactoryContext _db;

    public MachineController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(Machine => Machine.JoinEntities)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(Machine => Machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine Machine)
    {
      _db.Machines.Add(Machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine Machine)
    {
      _db.Entry(Machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine Machine, int EngineerId)
    {
      bool alreadyExists = _db.EngineerMachine.Any(EngineerMachine => EngineerMachine.MachineId == Machine.MachineId && EngineerMachine.EngineerId == EngineerId);
      if (EngineerId != 0 && !alreadyExists)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = Machine.MachineId });
      }
      _db.SaveChanges();
      if (alreadyExists)
      {
        return RedirectToAction("AddEngineerError");
      }
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineerError()
    {
      return View();
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(Machine => Machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("index");
    }
  }
}

Factory/Views/Machine/AddEngineer.cshtml
@model Factory.Models.Machine

<h2>Add a licenced Engineer</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("select engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save">
}

Factory/Views/Machine/AddEngineerError.cshtml
<h1>Error: That engineer was already added to this machine.</h1>

Factory/Views/Machine/Create.cshtml
@model Factory.Models.Machine

<h4>Add New Machine</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Operational)
  @Html.EditorFor(model => model.Operational)

  <input type="submit" value="Add a new Machine" />
}

Factory/Views/Machine/Delete.cshtml
@model Factory.Models.Machine

<h2>Are you sure you want to remove @Html.DisplayFor(model => model.Name)?</h2>

@using (Html.BeginForm())
{
  <button type="submit">Delete Machine</button>
}

Factory/Views/Machine/Details.cshtml
@model Factory.Models.Machine

<h2>Machine Details</h2>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<p>@Html.DisplayNameFor(model => model.Operational) @Html.DisplayFor(model => model.Operational)</p>

@if (@Model.JoinEntities.Count == 0)
{
  <p>There are no engineers licensed to repair this machine</p>
}
else
{
  <h4>Engineers</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Engineer.Name</li>
    @using (Html.BeginForm("DeleteEngineer", "Machine"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="Delete" />
    }
  }
  </ul>
}


<p>@Html.ActionLink("Add Licenced Engineer", "AddEngineer", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Edit Machine Details", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>

Factory/Views/Machine/Edit.cshtml
@model Factory.Models.Machine

<h4>Add New Machine</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Operational)
  @Html.EditorFor(model => model.Operational)

  <input type="submit" value="Edit Machine" />
}

Factory/Views/Machine/Index.cshtml
@using Factory.Models;
@model List<Factory.Models.Machine>

<h1>Machine</h1>
@if(@Model.Count == 0)
{
  <p>No Machines have been added</p>
}
<ul>
  @foreach(Machine Machine in Model)
  {
    <li>@Html.ActionLink($"{Machine.Name}", "Details", new { id = Machine.MachineId })</li>
  }
</ul>

<p>@Html.ActionLink("Add a new Machine", "Create")</p>